apiVersion: apps/v1
kind: Deployment
metadata:
  name: snippets-backend
  labels:
    app: snippets-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snippets-backend
  template:
    metadata:
      labels:
        app: snippets-backend
    spec:
      containers:
        - name: snippets-backend
          image: snippets-backend:v1
          ports:
            - containerPort: 3001
