name: Build

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: write

jobs:
  detect-changes:
    name: Detect Changes
    if: "!startsWith(github.event.head_commit.message, 'chore(frontend): bump')"
    runs-on: [self-hosted, Linux, X64]
    outputs:
      frontend: ${{ steps.changes.outputs.frontend }}
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            frontend:
              - 'frontend/**'

  build-frontend:
    needs: detect-changes
    if: needs.detect-changes.outputs.frontend == 'true'
    uses: ./.github/workflows/build-frontend.yml
